### ISSUE TITLE
Difference Between Windows 10 App and Plugin

### ISSUE THREAD

**Issue by lonkarjay** [truedread/netflix-1080p#112]
The difference is pretty drastic.
I'm sorry if this has been brought-up before.
I'm using a pretty old PC (Core2Duo E7500, 4GB RAM), running latest Windows 10 (21H1)

**Castlevania S03E03

Google Chrome:
Playing bitrate (a/v): 192 / 878 (1920x1080)

Microsoft Edge:
Playing bitrate (a/v): 128 / 878 (1920x1080)

Brave Beta:
Playing bitrate (a/v): 192 / 878 (1920x1080)

Windows 10 App:
Playing bitrate (a/v): 192 / 1685 (1920x1080)**

Rest all settings are default - VP9 enabled/disabled - no difference.
Ctrl + Alt + Shift + S options are also capped to 192/878 bit-rate.
Also, from browsers, I can't feel the same sound clarity as I get from the Win 10 app, the app, in my experience, produces the loudest and the clearest sound quality.

The Picture-Quality difference is also noticeably better on the app.

Attaching Win 10 App Screenshot for reference.
![1](https://user-images.githubusercontent.com/53859086/124293045-de2ac900-db73-11eb-9db9-8e56b212063d.png)

I appreciate all your efforts, and I hate the Win 10 App UI, but for now, I have no other choice than to use it for my optimum viewing experience.

Just my two cents, no hate!
Thank you for your consideration.

**Comment by vegardheimdal** [comment]
My bitrate caps - A/V

- Google Chrome  128 / 1336
- Win10 App   192 / 2080

**Comment by truedread** [comment]
So here's the deal. This extension gets the AVCHi encodes of Netflix streams, and the Windows 10 app gets the AVCMain encodes of Netflix streams. [According to Netflix](https://netflixtechblog.com/optimized-shot-based-encodes-now-streaming-4b9464204830), AVCHi has a better VMAF than AVCMain at lower bitrates, but I'd take that with a grain of salt since you've said that you've noticed that PQ is better with AVCMain. I wish I could get AVCMain with the Google Chrome ESN (back in 2018, when this extension was first conceived, that's what it used to be able to get). However, Netflix has restricted the Google Chrome ESN to only be able to get AVCHi. In other words, if I wanted to implement a way to get the AVCMain streams (which I agree are the best quality available), I would have to do some things that I would consider to be in a legal gray area (perhaps on the darker side of the gray, if you will). I really do wish I could implement this, and I'm going to keep this issue open as a reminder. I feel bad that you guys don't want to use this extension in favor of the Windows 10 app, but I'm a stickler for quality too (hey, that's why I made this), so I completely understand your decision. Thank you for pointing this out to me, but unfortunately I don't think there's that much I can do right now.

**Comment by lonkarjay** [comment]
No worries! Appreciate all the awesome work you do!
Takes a lot of determination, I understand!
Thank you! 🙌🏻🙏🏻

**Comment by truedread** [comment]
Also, a comment about the sound. The extension is only able to get a maximum of 128kbps AAC5.1. The highest bitrate Netflix streams can go up to 768kbps DD+5.1, which I wish I could implement with this extension. The problem is that Google Chrome cannot decode DD/DD+ because of licensing issues. This isn't something I can control, and I really wish Google obtained the proper licenses with Dolby to decode these superior audio codecs. The Windows 10 app can decode these codecs, and can thus stream audio at a much higher bitrate. I get the highest bitrate audio that Google Chrome can decode, and anything further is purely a limitation of the browser, unfortunately.

**Comment by lonkarjay** [comment]
Oh, I see. No problem, I think I'll close this issue.
Thank you for clearing things up.
I'm sure you'll find a legal and safe way to implement the optimum quality in the future! 🤘🏻

**Comment by serialpotato** [comment]
If anyone needs AVC in a browser then following extension does it.

**Comment by lonkarjay** [comment]
Thanks, @serialpotato!
This finally did it for me!
Solved all my issues and concerns!
I did use this plugin before, but just not on Edge, but on Brave Beta.
Many thanks!
