### ISSUE TITLE
Cadmium Playercore got updated again

### ISSUE THREAD

**Issue by Cysioland** [truedread/netflix-1080p#39]
And as such I get below-1000 bitrates

**Comment by scorpion421** [comment]
I hope, this tag-game will end as soon as Microsoft utilizes a Chromium based backend. I have the luck to get around with Microsoft Edge. But several users are happy with Linux, so... yeah. It's time for a change. Don't get me wrong: I love this extension. But it's for sure a pain in the back, to update it each and every time Netflix updates the Cadmium Playercore.

**Comment by Cysioland** [comment]
@scorpion421 Sadly, they might just make their current DRM system compatible with Chromium Edge, but incompatible with Chromium Chrome. I highly doubt they gonna go with Widevine.

**Comment by scorpion421** [comment]
Well... guess you're right... dunno why Netflix won't simply support Widevine. I'd go for it: Firefox + Chrome are the leaders of used browsers. Amazon uses it too. So it can't be such a problem. And just my two cents: If I have the chance to gain more customers by supporting Widevine: I'd do it. Linux users would be satisfied, probably 90% of all other users too, because using Edge is a pain in the back.
Not a bad browser, no. Just a browser, I won't use.

I just hope, we'll be able to reverse the implementation for Edge + Chromium backend, so devs can compile a Chromium based browser to finally support a tolerable playback at least for Windows - maybe a bridge for Widevine too (if that's even possible - we'll see).

**Comment by truedread** [comment]
Added in latest release.
