### ISSUE TITLE
can autoDismiss dialog?

### ISSUE THREAD

**Issue by vihuela** [truedread/netflix-1080p#88]
every video show，bitRate cdn select dialog  can show，close it was boring ....emm

**Comment by sylee23** [comment]
same here

**Comment by cherio** [comment]
Same. Whenever I let Netflix skip to the next episode on its own this dialog pops up

![image](https://user-images.githubusercontent.com/2200569/81256572-e6828500-8ffe-11ea-9513-0d9177c148ee.png)

It is a small price to pay though for a free extension and picture quality :) I even feel bad reporting it

**Comment by ItsNickBarry** [comment]
@cherio The "Override" button does not dismiss it?

**Comment by cherio** [comment]
I am a chicken when it comes to trying things I know nothing about :)

What exactly happens if I click override? Will it chose the selected server for this session only or permanently? Will this server be optimal when I watch another show? What if the server is taken down later? How do I change the selection later? Not knowing what will happen I simply cowardly exit and restart :)

**Comment by ItsNickBarry** [comment]
@cherio Any change to that menu is temporary.

**Comment by truedread** [comment]
Closing as major changes have been made that have probably fixed this.
